version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29-ndk
    steps:
      - checkout
      - run: 
          command: ./gradlew build
          environment: 
            CI: 'TRUE'